version: "2"
linters:
  default: standard
  exclusions:
    rules:
      - linters:
        - staticcheck
        text: "QF1008:"
    paths:
      - "vendor/*"
      - "cmd/.*/.*_test\\.go"
      - "internal/.*/.*_test\\.go"