# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Populate vendor dir
      run: go mod vendor

    - name: Install dependencies
      run: go install ./...

    - name: Build
      run: go build -v ./...

    - name: Patch missing executables
      run: touch ${RUNNER_TEMP}/condor_vault_storer ${RUNNER_TEMP}/condor_status ${RUNNER_TEMP}/condor_store_cred ${RUNNER_TEMP}/htgettoken

    - name: Test
      run: export PATH="${RUNNER_TEMP}:$PATH"; go test -v ./...
      env:
        PATH: "${RUNNER_TEMP}:/usr/bin:/usr/local/bin"
